"use client"; import {useState} from "react";
const people=[["Mom","mom"],["Dad","dad"],["Alice","alice"],["Juliet","juliet"]];
const seed=[{t:"08:15",title:"School",who:["Alice","Juliet"],end:"15:15"},{t:"15:30",title:"Hockey training",who:["Alice"],end:"17:00",place:"Sports Centre"},{t:"17:00",title:"Hockey pickup",who:["Dad","Alice"],end:"17:20"},{t:"18:00",title:"Swimming",who:["Juliet","Mom"],end:"19:00",place:"City Pool"}];
export default function Home(){const [tab,setTab]=useState("Today"); const [events,setEvents]=useState(seed); const [requests,setRequests]=useState(2); const [open,setOpen]=useState(false);
return <main><header><div><small>FAMILY CALENDAR</small><h1>{tab}</h1><p>Friday, 18 September</p></div><button className="bell" onClick={()=>setTab("Requests")}>🔔<b>{requests}</b></button></header>
<div className="people"><button className="active">Everyone</button>{people.map(([n,c])=><button key={n}><i className={c}/>{n}</button>)}</div>
{tab==="Today"&&<section><div className="sectionTitle"><h2>Today</h2><span>{events.length} commitments</span></div>{events.map((e,i)=><article className="event" key={i}><time>{e.t}</time><div className={"bar "+e.who[0].toLowerCase()}/><div><h3>{e.title}</h3><p>{e.who.map(w=><span className="tag" key={w}>{w}</span>)} until {e.end}</p>{e.place&&<p className="muted">⌖ {e.place}</p>}</div></article>)}<div className="notice">✓ No family conflicts detected today</div></section>}
{tab==="Week"&&<section><div className="sectionTitle"><h2>This week</h2><span>14–20 Sep</span></div>{["MON 14","TUE 15","WED 16","THU 17","FRI 18","SAT 19","SUN 20"].map((d,i)=><div className="day" key={d}><b>{d}</b><div className="lanes">{people.map(([n,c],j)=><span className={c} style={{height:12+((i+j*2)%4)*8}} title={n}/>)}</div></div>)}</section>}
{tab==="Month"&&<section><div className="sectionTitle"><h2>September</h2><span>2026</span></div><div className="month">{Array.from({length:30},(_,i)=><div className={i+1===18?"today":""} key={i}><b>{i+1}</b>{[0,1,2].slice(0,(i%4)).map(x=><i key={x} className={people[(i+x)%4][1]}/>)}</div>)}</div></section>}
{tab==="Family"&&<section><div className="sectionTitle"><h2>Family</h2><span>Next commitments</span></div>{people.map(([n,c])=><article className="personCard" key={n}><i className={c}/><div><h3>{n}</h3><p>{n==="Alice"?"Hockey · 15:30":n==="Juliet"?"Swimming · 18:00":n==="Dad"?"Pickup Alice · 17:00":"Swimming with Juliet · 18:00"}</p></div></article>)}</section>}
{tab==="Requests"&&<section><div className="sectionTitle"><h2>Needs approval</h2><span>{requests} pending</span></div>{requests>0?<><Request name="Alice" text="Movie with Emma" detail="Sat · 18:00–21:00" act={()=>setRequests(x=>x-1)}/>{requests>1&&<Request name="Juliet" text="Sleepover at Sophie's" detail="Fri 17:00 → Sat 10:00" act={()=>setRequests(x=>x-1)}/>}</>:<div className="empty">All caught up ✓</div>}</section>}
<button className="fab" onClick={()=>setOpen(true)}>＋</button>
<nav>{["Today","Week","Month","Family"].map(x=><button onClick={()=>setTab(x)} className={tab===x?"selected":""} key={x}><span>{x==="Today"?"◉":x==="Week"?"▥":x==="Month"?"▦":"♧"}</span>{x}</button>)}</nav>
{open&&<div className="sheet"><div className="form"><button className="close" onClick={()=>setOpen(false)}>×</button><small>NEW EVENT</small><h2>Add to the family</h2><label>What?<input id="title" placeholder="e.g. Swimming"/></label><label>Who?</label><div className="choices">{people.map(([n,c])=><button key={n}><i className={c}/>{n}</button>)}</div><div className="row"><label>Date<input type="date" defaultValue="2026-09-23"/></label><label>Time<input type="time" defaultValue="18:00"/></label></div><label>Repeat<select><option>Doesn't repeat</option><option>Every week</option><option>Every 2 weeks</option><option>Custom…</option></select></label><label>Where<input placeholder="Location"/></label><button className="primary" onClick={()=>{setEvents([...events,{t:"18:00",title:"New family event",who:["Alice"],end:"19:00"}]);setOpen(false)}}>Add event</button></div></div>}</main>}
function Request({name,text:tx,detail,act}:{name:string,text:string,detail:string,act:()=>void}){return <article className="request"><span className={"avatar "+name.toLowerCase()}>{name[0]}</span><div><small>{name.toUpperCase()} REQUESTED</small><h3>{tx}</h3><p>{detail}</p><div><button>Decline</button><button className="approve" onClick={act}>Approve</button></div></div></article>}